// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'ap-northeast-1:77633922-a638-4fd3-af75-6f965b3cc83b',
    'aws_cognito_region': 'ap-northeast-1',
    'aws_mobile_analytics_app_id': '07eb463ede2146068f23d1d4abc53f28',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '7310f6d5-c315-4f3c-98dc-1abb3ba0c211',
    'aws_project_name': 'iot-mobile',
    'aws_project_region': 'ap-northeast-1',
    'aws_resource_name_prefix': 'iotmobile-mobilehub-1497933623',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'iotmobile-userfiles-mobilehub-1497933623',
    'aws_user_files_s3_bucket_region': 'ap-northeast-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'ap-northeast-1_2KoxZ8JxR',
    'aws_user_pools_web_client_id': '7rooch3tnp8mltnufbenklcq1b',
    'aws_appsync_graphqlEndpoint': 'https://r4n5j6hiy5c2jii7cwwejdgboy.appsync-api.ap-northeast-1.amazonaws.com/graphql',
    'aws_appsync_region': 'ap-northeast-1',
    'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS',
}

export default awsmobile;
